### ISSUE TITLE
Add command fails with Attribute Error

### ISSUE THREAD

**Issue by nriaziat** [RobertJN64/TKinterModernThemes#11]
Hi, 

I am using the following line of code to bind a command within a GUI class. 

`self.model_type_frame.Radiobutton("Multi-Isotherm", variable=self.model_name, value="multiisotherm", command=self.model_selection)`

Upon running the GUI object, the following error is raised: 

`AttributeError: 'functools.partial' object has no attribute '__name__'. Did you mean: '__ne__'?`

Binding functions for the Button type works just fine, this seems to be just on the RadioButton as far as I can tell.

**Comment by RobertJN64** [comment]
Found the issue (it has to do with the automatic partial wrapping TKMT does. I am publishing a new release to fix.

**Comment by RobertJN64** [comment]
Fixed in version 1.10.4.
