### ISSUE TITLE
Typo error in readme.md

### ISSUE THREAD

**Issue by SNEAXIII** [RobertJN64/TKinterModernThemes#3]
Hello, you've made a small error in your documentation. In the "Resizable Windows" field, you write:

> "This can be disabled with the **_cleanResize_** parameter in run()".

But in the method, the parameter is called **_cleanresize_** without capitals, maybe you forgot the camelcase typo :)

thanks for your work :)

ps: can you please provide the code you use to make your screenshot? thank you ^^

**Comment by RobertJN64** [comment]
Fixed! Camel case would have been the correct styling based on the rest of the code base, but I changed the README instead to ensure backwards compatibility (at least until a major version update). 

The code for the screenshots is just the `allwidgets` example that is provided with the library. https://github.com/RobertJN64/TKinterModernThemes/blob/master/TKinterModernThemes/examples/allwidgets.py
