### ISSUE TITLE
Suggestion: More customisability

### ISSUE THREAD

**Issue by GloriousGlider8** [RobertJN64/TKinterModernThemes#6]
Instead of being limited to 3 themes (or 6 for light & dark), a function could instead offer more customisability.

The function would work like this:
TKMT.GenerateTheme(name, mode, foreground, background, accent)
name: the name of the theme
mode: light or dark (this affects other things such as the text color)
foreground: foreground color (button background e.t.c, can be RGB, HEX whichever is easier to implement)
background: background color (window background, can be RGB, HEX whichever is easier to implement)
accent: accent color (selected checkbox color e.t.c, can be RGB, HEX whichever is easier to implement)

This would then generate a folder in the script's directory where there would be the tcl and resources files.
This would be a great idea and would allow more color themes!

**Comment by RobertJN64** [comment]
The themes in TKMT were created by https://github.com/rdbende and have many .png files that make up the elements. I don't current have a way to generate these automatically - but if that code were to be written I would be happy to add it.

**Comment by GloriousGlider8** [comment]
I will try to make some code to do that and, if you want, submit a PR to add the code.
