### ISSUE TITLE
Float type in IntVar

### ISSUE THREAD

**Issue by OlegXio** [RobertJN64/TKinterModernThemes#9]
![Screenshot](https://github.com/RobertJN64/TKinterModernThemes/assets/125251033/a67cba7d-c283-457c-b6e3-34000e7c0712)
```python
self.password_length = tk.IntVar(value=25)
self.Scale(100, 0, self.password_length, row=1, col=0).grid(row=2, column=0, sticky='w')
self.pswlenght = ttk.Label(self.master, textvariable=self.password_length, width=50).grid(row=2, column=1)
```
In the above code snippet, you can see that a variable of Int type is set for the slider, but when we try to print it, we get a value of float type. We could set text=int(password_lenght.get()) instead of textvariable for ttk.Label, but this is not an updatable function. It could be updated if Scale had the ability to set the attribute command=updatescale_handler.

When trying to use StringVar, DoubleVar instead of IntVar the identical situation occurs (despite the fact that the Scale widget should accept only IntVar or DoubleVar in variable:
```
WidgetFrame.py:971 :
def Scale(self, lower: float, upper: float, variable: Union[tk.IntVar, tk.DoubleVar] <....>)

**Comment by RobertJN64** [comment]
Sadly, the **ttk** scale widget does not have the same customization as the **tk** version. However, we can work around this using a function like you suggest, here is an example:

```python
import TKinterModernThemes as TKMT
import tkinter as tk

class App(TKMT.ThemedTKinterFrame):
    def __init__(self, theme, mode, usecommandlineargs=True, usethemeconfigfile=True):
        super().__init__("Image", theme, mode, usecommandlineargs=usecommandlineargs,
                         useconfigfile=usethemeconfigfile)

        self.password_length = tk.IntVar(value=25)
        self.output = tk.StringVar(value="25")

        self.frame = self.addLabelFrame("Frame")
        self.frame.Scale(0, 100, self.password_length, widgetkwargs={"command": self.handle_update})
        self.pswlenght = self.frame.Text("", widgetkwargs={"textvariable":self.output})

        self.run()

    def handle_update(self, val):
        self.output.set(str(round(float(val))))

if __name__ == "__main__":
    App("park", "dark")
```
